perf :zap: Improved Event and Transaction commitment performance
KasarLabs/deoxys-fork pull request #133
Opened 2024-02-23 22:11 UTC by Trantorian1

# Pull Request type

- Refactoring (no functional changes, no API changes)

## What is the current behavior?

[`fetch_block`](https://github.com/KasarLabs/deoxys/blob/3b43b3b439c853ab1f3b9b2a4ce29e10f9c767a7/crates/client/deoxys/src/l2.rs#L214) calls take too long, lasting over 1s in some case for transaction/event-heavy blocks. This used to be due to inefficiencies in the way in which [transaction](https://github.com/KasarLabs/deoxys/blob/3b43b3b439c853ab1f3b9b2a4ce29e10f9c767a7/crates/client/deoxys/src/commitments/transactions.rs#L57) and in particular [event](https://github.com/KasarLabs/deoxys/blob/main/crates/client/deoxys/src/commitments/events.rs) commitments were calculated, but is now caused by [updating the state root](https://github.com/KasarLabs/deoxys/blob/3f00b99d559e5f296808a87bc5a3737bcec96dfc/crates/client/deoxys/src/l2.rs#L457C22-L457C39) after #134 . 

This is due to the cost of calculating the Merkle Root in the Bonsai db: as new nodes are added to the trie, it's size rapidly grows since content nodes can only be added as leafs. This greatly increases the amount of hashes to compute in order to determine the root.

Performance testing and statistical analysis of Deoxys has shown this to be a major issue, causing heavy slowdowns of other Substrate processes, resulting in exponential $O(b^N)$ temporal complexity (measured by [experiment](https://www.desmos.com/calculator/zqbxcr0wpr)).

Resolves #94 

## What is the new behavior?

While no direct changes were able to be made to the way in which the Merkle Root is calculated (ie: no changes were made to the underlying recursive algorithms in the [bonsai trie lib](https://github.com/keep-starknet-strange/bonsai-trie)), the following steps were taken to gain perfomance:

- Contract trie root computations have been parallelized and are now run in a blocking-safe thread.
- Transaction and event commitments have been parallelized, and are now computed independently and at the same time.
- Transaction and event hash computation have also been parallelized.

This has lead to a *significant* increase in performance, down to a complexity of $O(N)$ (measured by [experiement](https://www.desmos.com/calculator/zqbxcr0wpr)), with a *decrease in execution time of up to 99%* in some cases.

## Benchmarking

Thorough benchmarking was applied over the first `5800` blocks. Testing of the unoptimized version of the code had to be halted at block `2900` due to ballooning complexity, while testing of the optimized version of the code continued until block `5600`. 

Benchmark results were also compared to growth in number of events, transactions and contracts in new blocks to see if a strong link could be established in regards to the slowdowns. This has shown similarities between the rate of increase in contracts and execution time, while new events do not seem to impact performance. Rate of transaction increase follows a similar trend but has been shown to have little impact on performance, with [updating the contract trie root](https://github.com/KasarLabs/deoxys/blob/3f00b99d559e5f296808a87bc5a3737bcec96dfc/crates/client/deoxys/src/commitments/lib.rs#L162) remaining the major bottleneck.

The complete sets of benchmark results along with visual representations can be found [here](https://www.desmos.com/calculator/zqbxcr0wpr).

> :bulb:  Note that these benchmarks were run on an Intel Xeon-E 2288G - 8c/16t. Due to the multithreaded nature of these improvements, performance might vary across CPUs with less threads.

## Does this introduce a breaking change?

No. Nodes with an existing local database can keep synchronizing new blocks, albeit at a faster rate.

## Other information

> :warning: The main bottleneck remains in the computation of the Merkle Root of the Bonsai Trie. Major improvements might still be made there.

2024-02-23 22:56 UTC, nils-mathieu requested changes
There's some inefficiencies when spawning tasks.

Other than that, I'm not familiar enough with the problem to have any opinion on the correctness of the algorithm.

2024-02-23 22:56 UTC, nils-mathieu commented on crates/client/deoxys/src/commitments/events.rs
> +        let arc_event = Arc::new(event);
Using an `Arc` here just creates an unnecessary allocation. Your event is already cloned (because you called `.cloned()` on your iterator. `get_hash` takes are regular refernence, no need to use reference counting

```rust
for (i, event) in events.iter().cloned().enumerate() {
    set.spawn(async move { (i, get_hash::<H>(&event)) });
}
```

Also, be careful. If calling `get_hash` really *is* expansive, then you're probably slowing down you're whole async executor. If you want to schedule a blocking call, use `spawn_blocking` instead of a regular `spawn`. That will make sure that Tokio runs the task on a thread that can afford to be blocked.

2024-02-23 22:56 UTC, nils-mathieu commented on crates/client/deoxys/src/commitments/events.rs
> +) -> Result<Felt252Wrapper, String>
why move from `anyhow::Error` to `String`?

2024-02-23 22:56 UTC, nils-mathieu commented on crates/client/deoxys/src/commitments/transactions.rs
> +        let arc_tx = Arc::new(tx);
Same thing here: you don't need to allocate an `Arc`. Just move the value into the future without `Arc`ing it.

And for the same exact reason, you should be using `spawn_blocking` instead of `spawn`.

2024-02-23 22:56 UTC, nils-mathieu commented on crates/client/deoxys/src/commitments/transactions.rs
> +) -> Result<Felt252Wrapper, String>
Same thing here: why not `anyhow::Error`?

2024-02-27 05:36 UTC, Trantorian1 commented on crates/client/deoxys/src/commitments/events.rs
> +        let arc_event = Arc::new(event);
Thanks, dully noted! This part of the algorithm has since been overhauled in #134 but I have applied your remark to the new code, my bad :sweat_smile:

2024-02-27 05:39 UTC, Trantorian1 commented on crates/client/deoxys/src/commitments/events.rs
> +) -> Result<Felt252Wrapper, String>
At the time this was for two reasons:

1. No error was actually being returned as `commit`s to the Bonsai db were being called with `unwrap`, so it seemed to me the error type was not important.
2. I feel like we might be using anyhow a bit too much for errors that do not need as much genericity, so I am trying to cut down on that whenever I get the chance.

Let me know what you think though!

2024-02-27 05:42 UTC, Trantorian1 commented on crates/client/deoxys/src/commitments/transactions.rs
> +        let arc_tx = Arc::new(tx);
Noted! Our hash computation is actually different from the hash computation inside the Bonsai lib, which is the one which is expensive. In comparison, calculating the hash on our side is mostly negligible, with committing to the Bonsai db being the main bottleneck due to recursive hashing of the many nodes of the trie. Steps have been taken to run that in `spawn_blocking` where applicable though, as seen in recent commits.

2024-02-27 05:43 UTC, Trantorian1 commented on crates/client/deoxys/src/commitments/transactions.rs
> +) -> Result<Felt252Wrapper, String>
Same as above, cutting down on un-used genericity in error return types.

2024-02-27 07:40 UTC, nils-mathieu commented on crates/client/deoxys/src/commitments/events.rs
> +) -> Result<Felt252Wrapper, String>
Here are my main points:

- anyhow is not generic, so you don't need to worry about monomorphisation costs.

- It works basically like a `String` minus the actual string allocation (there is actually an allocation as well under the hood, but it is much smaller in a vast majority of cases).

- You can turn any error type into an `anyhow::Error` just by calling the `?` operator. With a `String` you have to manually create it with `format!`, which can be become redundant.

- `anyhow::Result<T>` or `Result<T, anyhow::Error>` is arguably clearer than `Result<T, String>`.

- You get to use cool macros to make the code shorter and cleaner.

```rust
function_that_fails()?;
// or
function_that_fails().context("function has failed")?;

// vs
function_that_fails().map_err(|err| format!("function has failed: {}", err))?;
```

```rust
bail!("my custom error");
// vs
return Err(String::from("my custom error"));

ensure!(condition, "oh no");
// vs
if condition {
    return Err(String::from("oh no"));
}
```

That being said, when possible, I'd lean more toward creating a custom error type. But that really depends on whether the error needs to be caught or not. If you only need to print an error that's not supposed to occur, `anyhow` or `String` are functionally the same (though I like anyhow better). In all other cases, creating a custom error type is strictly better (though it takes a bit more effort to maintain).

2024-02-27 07:41 UTC, nils-mathieu commented on crates/client/deoxys/src/commitments/events.rs
> +) -> Result<Felt252Wrapper, String>
Now that I'm reading your answers again, I'm not sure whether we're using the same definition of "generic". What do you mean by "do not need as much genericity" ?

2024-02-27 08:58 UTC, antiyro approved these changes

2024-02-27 08:59 UTC, merged